FROM nginx:alpine

# Install curl for healthcheck
RUN apk add --no-cache curl

# Copy production nginx configuration
COPY nginx.prod.conf /etc/nginx/nginx.conf

# Expose HTTP
EXPOSE 8001
# Uncomment this if you want to expose HTTPS via a SSL certificate
# EXPOSE 443

# Default command provided by base image starts nginx